server:
  port: 8081

spring:
  application:
    name: nbc-scheduler-develop
  datasource:
    url: jdbc:mysql://localhost:3306/scheduler_develop
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE